CREATE TABLE BANK_USER (
    USER_ID INTEGER PRIMARY KEY,
    FIRSTNAME VARCHAR2(50),
    LASTNAME VARCHAR2(50)
);
/

CREATE TABLE BANK_ACCOUNTS (
    ACCOUNT_ID INTEGER PRIMARY KEY,
    ACCOUNT_NUM NUMBER,
    USER_ID NUMBER,
    ACCOUNT_NAME VARCHAR2(50),
    BALANCE INTEGER
);
/

--ADDING THE FK CONSTAINT
ALTER TABLE BANK_ACCOUNTS
ADD CONSTRAINT FK_ACCOUNT_USER_ID
FOREIGN KEY (USER_ID) REFERENCES BANK_USER(USER_ID);
/

--PK GENERATION
CREATE SEQUENCE SQ_ACCOUNT_ID
START WITH 10
INCREMENT BY 5;
/
CREATE SEQUENCE SQ_USER_ID
START WITH 10
INCREMENT BY 5;
/

ALTER TABLE BANK_USER
DROP CONSTRAINT FK_USER_ACCOUNT_ID;
/

INSERT ALL
INTO BANK_USER
VALUES(1,'Jake', 'Mulrenin')
INTO BANK_USER
VALUES(2,'EMMA','BANKS')
SELECT * FROM DUAL;
/
INSERT ALL 
INTO BANK_ACCOUNTS
VALUES(1,100,1,'Jakes Account',10000.00)
INTO BANK_ACCOUNTS
VALUES(2,101,2,'Emmas Account',20000.00)
SELECT * FROM DUAL;

SELECT * FROM BANK_ACCOUNTS
INNER JOIN BANK_USER ON BANK_USER.USER_ID = BANK_ACCOUNTS.USER_ID
WHERE BANK_USER.USER_ID = 2;

ALTER TABLE BANK_ACCOUNTS
ADD CONSTRAINT CHECK_MONEY
CHECK (BALANCE > 0);




