-- 2.1
SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE 
WHERE LASTNAME = 'King';

SELECT * FROM EMPLOYEE 
WHERE FIRSTNAME = 'Andrew' AND REPORTSTO IS NULL;

-- 2.2
SELECT * FROM ALBUM
ORDER BY TITLE DESC;

SELECT FIRSTNAME FROM CUSTOMER
ORDER BY CITY ASC;

-- 2.3
INSERT INTO GENRE VALUES (26, 'Country');
INSERT INTO GENRE VALUES (27, 'Disney Theme Songs');

INSERT INTO EMPLOYEE VALUES (9, 'Jaeger', 'Kaleigh', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO EMPLOYEE VALUES (10, 'Trevino', 'Danny', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO CUSTOMER VALUES (60, 'Kaleigh', 'Jaeger', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'kjaeger@gmail.com', NULL);
INSERT INTO CUSTOMER VALUES (61, 'Danny', 'Trevino', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dtrev@gmail.com', NULL);

--2.4
UPDATE CUSTOMER SET LASTNAME = 'Walter'
WHERE LASTNAME = 'Mitchell';
UPDATE CUSTOMER SET FIRSTNAME = 'Robert'
WHERE FIRSTNAME = 'Aaron';

UPDATE ARTIST SET NAME = 'CCR'
WHERE NAME = 'Creedence Clearwater Revival';

--2.5	
SELECT * FROM INVOICE
WHERE BILLINGADDRESS LIKE 'T%';

--2.6
SELECT * FROM INVOICE
WHERE TOTAL BETWEEN 15 AND 50;

SELECT EMPLOYEEID FROM EMPLOYEE
WHERE HIREDATE BETWEEN '01-JUN-03' AND '01-MAR-04';

--2.7
ALTER TABLE INVOICE
DROP CONSTRAINT FK_INVOICECUSTOMERID;
DELETE FROM CUSTOMER
WHERE FIRSTNAME = 'Robert' AND LASTNAME = 'Walter'; 
