DROP TABLE ACCOUNTS;
DROP TABLE USER_BANK;
DROP TABLE BEAR;
DROP TABLE BEAR_BEEHIVE;
DROP TABLE BEAR_TYPE;
DROP TABLE BEEHIVE;
DROP TABLE CAVE;
/
--CREATE TABLES
CREATE TABLE USER_BANK (
    USER_ID INTEGER PRIMARY KEY,
    FIRST_NAME VARCHAR2(30),
    LAST_NAME VARCHAR2(30)
);
/
CREATE TABLE ACCOUNTS (
    ACCOUNT_ID INTEGER PRIMARY KEY,
    USER_ID INTEGER,
    USER_NAME VARCHAR2(30),
    ACCOUNT_NAME VARCHAR2(30),
    BALANCE NUMBER
);

--ADD INFORMATION
INSERT ALL
INTO USER_BANK 
VALUES (1,'John','Williams')
INTO USER_BANK
VALUES (2,'Ben','Johnson')
INTO USER_BANK
VALUES (3,'Natally','Smith')
SELECT * FROM DUAL;
/
INSERT ALL
INTO ACCOUNTS
VALUES (1, 1, 'JWILL', 'CHECKING', 0.69)
INTO ACCOUNTS
VALUES (2, 2, 'BJOHN', 'SAVING', 300.50)
INTO ACCOUNTS
VALUES (3, 3, 'NSMI', 'CHECKING', 1000.75)
SELECT * FROM DUAL;
/
SELECT BALANCE, ACCOUNT_NAME
FROM ACCOUNTS
WHERE USER_NAME = 'JWILL';
/
INSERT INTO USER_BANK VALUES (4, 'Mike', 'Adams');
/
--JOIN USERS AND THEIR ACCOUNTS
SELECT *
FROM USER_BANK U --ALIAS BEAR TABLE 
FULL JOIN ACCOUNTS ON U.USER_ID = ACCOUNTS.USER_ID;
/
--FIRST, SOME CHECKS
ALTER TABLE ACCOUNTS ADD CONSTRAINT CK_BALANCE_POSITIVE
CHECK (BALANCE > 0);
/

--NOW, THE PROCEDURE
CREATE OR REPLACE PROCEDURE SP_WITHDRAW_MONEY(B_ID IN NUMBER, H_ID IN NUMBER, HONEY_AMT IN NUMBER, AMT_FED OUT NUMBER)
IS
BB_EXISTS INTEGER;
BEGIN
    --CHECK THAT THIS BEAR IS CORRECTLY MATCHED TO THIS BEEHIVE
    SELECT COUNT(BB.BEAR_ID) INTO BB__EXISTS
    FROM BEAR_BEEHIVE BB
    WHERE BB.BEAR_ID = B_ID
    AND BB.BEEHIVE_ID = H_ID;
    DBMS_OUTPUT.PUT_LINE(BB_EXISTS);
    IF BB_EXISTS > 0 AND HONEY_AMT > 0 THEN
    --DECREASE BEEHIVE WEIGHT
        UPDATE BEEHIVE SET LBS_HONEY = LBB_HONEY-HONEY_AMT
        WHERE BEEHIVE_ID = H_ID;
        --INCREASE BEAR WHEIGHT
        UPDATE BEAR SET WEIGHT = WEIGHT+HONEY_AMT
        WHERE BEAR_ID = B_ID;
        --SET THE RETURN VALUE
        AMT_FED := HONEY_AMOUNT;
    ELSE
    DBMS_OUTPUT.PUT_LINE('FAILED TO FEED BEAR');
    AMT_FED := 0;
    END IF;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        --DBMS_OUTPUT.PUT_LINE('FAILED TO FEED BEAR');
        AMT_FED := 0;
        ROLLBACK;
END;