DROP TABLE ACCOUNTS;
DROP TABLE USER_BANK;
DROP TABLE BEAR;
DROP TABLE BEAR_BEEHIVE;
DROP TABLE BEAR_TYPE;
DROP TABLE BEEHIVE;
DROP TABLE CAVE;
/
--CREATE TABLES
CREATE TABLE USER_BANK (
    USER_ID INTEGER PRIMARY KEY,
    FIRST_NAME VARCHAR2(30),
    LAST_NAME VARCHAR2(30)
);
/
CREATE TABLE ACCOUNTS (
    ACCOUNT_ID INTEGER PRIMARY KEY,
    USER_ID INTEGER,
    USER_NAME VARCHAR2(30),
    ACCOUNT_NAME VARCHAR2(30),
    BALANCE NUMBER
);

--ADD INFORMATION
INSERT ALL
INTO USER_BANK 
VALUES (1,'John','Williams')
INTO USER_BANK
VALUES (2,'Ben','Johnson')
INTO USER_BANK
VALUES (3,'Natally','Smith')
SELECT * FROM DUAL;
/
INSERT ALL
INTO ACCOUNTS
VALUES (1, 1, 'JWILL', 'CHECKING', 0.69)
INTO ACCOUNTS
VALUES (2, 2, 'BJOHN', 'SAVING', 300.50)
INTO ACCOUNTS
VALUES (3, 3, 'NSMI', 'CHECKING', 1000.75)
SELECT * FROM DUAL;
