INSERT INTO USER_ROLES (TITLE) VALUES ('Administrator');
INSERT INTO USER_ROLES (TITLE) VALUES ('User');

INSERT INTO USERS (USER_NAME, USER_PASS, ROLE_ID) VALUES (1, 'darkKnight74', 'IAmBatman', 1); 
INSERT INTO USERS (USER_NAME, USER_PASS, ROLE_ID) VALUES (2, 'splitPersonality11', 'IAmTwoFace', 2);


