INSERT INTO USER_ROLES (ROLE) VALUES ('Member');
INSERT INTO USER_ROLES (ROLE) VALUES ('Admin');

INSERT INTO USERS(USERNAME, EMAIL, PASSWORD, ROLE_ID) VALUES('kevin', 'kevin@gmail.com', '123', 3);
INSERT INTO USERS(USERNAME, EMAIL, PASSWORD, ROLE_ID) VALUES('james', 'james@gmail.com', '456', 4);