INSERT INTO USER_ROLES VALUES (1, MEMBER);
INSERT INTO USER_ROLES VALUES (2, ADMIN);

INSERT INTO USER (USER_ID, NAME, USERNAME, PASSWORD, USER_ROLE_ID) VALUES (1, "Bowser", "KoopaKing", "KBK123", 2);
INSERT INTO USER (USER_ID, NAME, USERNAME, PASSWORD, USER_ROLE_ID) VALUES (2, "Goomba", "Goomba", "G123", 2);
INSERT INTO USER (USER_ID, NAME, USERNAME, PASSWORD, USER_ROLE_ID) VALUES (3, "Koopa", "KoopaTroopa", "KT123", 2);
INSERT INTO USER (USER_ID, NAME, USERNAME, PASSWORD, USER_ROLE_ID) VALUES (4, "Lakitu", "CloudGuy", "L123", 2);
INSERT INTO USER (USER_ID, NAME, USERNAME, PASSWORD, USER_ROLE_ID) VALUES (5, "BulletBill", "BulletBill", "BB123", 2);
INSERT INTO USER (USER_ID, NAME, USERNAME, PASSWORD, USER_ROLE_ID) VALUES (6, "Thwomp", "HeavyWeight", "T123", 2);
INSERT INTO USER (USER_ID, NAME, USERNAME, PASSWORD, USER_ROLE_ID) VALUES (7, "Boo", "ShyGhost", "B123", 2);

COMMIT;