--CREATE TABLE USER_ROLE (
--	USER_ROLE_ID INT PRIMARY KEY AUTO_INCREMENT,
--	USER_ROLE_NAME VARCHAR2(10) NOT NULL
--);
--
--CREATE TABLE APPUSER (
--	APPUSER_ID INT PRIMARY KEY AUTO_INCREMENT,
--	FIRST_NAME VARCHAR2(30) NOT NULL,
--	LAST_NAME VARCHAR2(30) NOT NULL,
--	EMAIL VARCHAR2(100) NOT NULL UNIQUE,
--	PASSWORD VARCHAR2(30) NOT NULL,
--	USER_ROLE_ID INT NOT NULL
--);
--
--ALTER TABLE APPUSER
--ADD CONSTRAINT FK_APPUSER_USER_ROLE_URID
--FOREIGN KEY (USER_ROLE_ID) REFERENCES USER_ROLE(USER_ROLE_ID);

INSERT INTO USER_ROLE (USER_ROLE_ID, USER_ROLE_NAME)
VALUES (1, 'ADMIN');
INSERT INTO USER_ROLE (USER_ROLE_ID, USER_ROLE_NAME)
VALUES (2, 'MEMBER');

INSERT INTO APPUSER (APPUSER_ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, USER_ROLE_ID)
VALUES (1, 'Eddy', 'Soma', 'esoma.sesi@mailinator.com', 'esoma123456', 1);
INSERT INTO APPUSER (APPUSER_ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, USER_ROLE_ID)
VALUES (2, 'Jessica', 'Renzi', 'jrenzi.sesi@mailinator.com', 'jrenzi123456', 1);
INSERT INTO APPUSER (APPUSER_ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, USER_ROLE_ID)
VALUES (3, 'Tony', 'Simpson', 'tsimpson.sesi@mailinator.com', 'tsimpson123456', 2);
INSERT INTO APPUSER (APPUSER_ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, USER_ROLE_ID)
VALUES (4, 'Jane', 'Wilson', 'jwilson.sesi@mailinator.com', 'jwilson123456', 2);
INSERT INTO APPUSER (APPUSER_ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, USER_ROLE_ID)
VALUES (5, 'Blake', 'Kruppa', 'bkruppa.sesi@mailinator.com', 'bkruppa123456', 2);
INSERT INTO APPUSER (APPUSER_ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, USER_ROLE_ID)
VALUES (6, 'Mitch', 'Revature', 'mrevature.sesi@mailinator.com', 'mrevature123456', 2);
INSERT INTO APPUSER (APPUSER_ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, USER_ROLE_ID)
VALUES (7, 'Carlos', 'Bejar', 'cbejar.sesi@mailinator.com', 'cbejar123456', 2);

COMMIT;