INSERT INTO USER VALUES (1, 'JOHN DOE', 'JOHNDOE@GMAIL.COM')
INSERT INTO USER VALUES (2, 'JANE DOE', 'JANEDOE@GMAIL.COM')
INSERT INTO USER VALUES (3, 'TOM SMITH', 'TOMSMITH@GMAIL.COM')
INSERT INTO USER VALUES (4, 'TERRI SMITH', 'TERRISMITH@GMAIL.COM')

INSERT INTO USERROLE VALUES (1, 'MEMBER')
INSERT INTO USERROLE VALUES (2, 'MEMBER')
INSERT INTO USERROLE VALUES (3, 'ADMIN')
INSERT INTO USERROLE VALUES (4, 'ADMIN')

COMMIT;