INSERT INTO PERSON (USER_ID, USER_NAME, USER_EMAIL, USER_USERNAME) VALUES (1, 'JOHN DOE', 'JOHNDOE@GMAIL.COM', 'JOHNDOE');
INSERT INTO PERSON (USER_ID, USER_NAME, USER_EMAIL, USER_USERNAME) VALUES (2, 'JANE DOE', 'JANEDOE@GMAIL.COM', 'JANEDOE');
INSERT INTO PERSON (USER_ID, USER_NAME, USER_EMAIL, USER_USERNAME) VALUES (3, 'TOM SMITH', 'TOMSMITH@GMAIL.COM', 'TOMSMITH');
INSERT INTO PERSON (USER_ID, USER_NAME, USER_EMAIL, USER_USERNAME) VALUES (4, 'TERRI SMITH', 'TERRISMITH@GMAIL.COM', 'TERRISMITH');


INSERT INTO USERROLE VALUES (1, 'MEMBER');
INSERT INTO USERROLE VALUES (2, 'MEMBER');
INSERT INTO USERROLE VALUES (3, 'ADMIN');
INSERT INTO USERROLE VALUES (4, 'ADMIN');

COMMIT;