DROP TABLE JSR_ACCOUNT;

CREATE TABLE JSRACCOUNT (
    ACCOUNTID INTEGER PRIMARY KEY,
    ACCOUNTNUMBER INTEGER,
    ACCOUNTUSER VARCHAR2(100),
    ACCOUNTNAME VARCHAR2(100),
    ACCOUNTBALANCE INT 
);

CREATE TABLE JSRUSER (
USERID INTEGER,
FIRSTNAME VARCHAR2(100),
LASTNAME VARCHAR2(100)
);
/

DROP TABLE ACCOUNT_JRS;

select * from jsruser;

select * from jsraccount;

ALTER TABLE JSRACCOUNT ADD FOREIGN KEY(USERID)
REFERENCES JSRUSER(USERID);

    